<?php

namespace Kaili;

/**
 * Test class for Directory.
 * Generated by PHPUnit on 2011-10-22 at 10:55:52.
 */
class DirectoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Directory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $test_dirs = array(
            ROOT.DS.'test_dir',
            ROOT.DS.'test_new_dir',
            SYSTEM.DS.'test_dir',
        );
        foreach($test_dirs as $f){
            is_dir($f) and rmdir($f);
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    
    /**
     * Test for Directory::factory()
     * @test
     */
    public function test_factory()
    {
        $object = Directory::factory(ROOT.DS.'application');
        $this->assertEquals($object->get_path(), ROOT.DS.'application');
    }
    
    /**
     * Test for Directory::factory()
     * The directory doesn't exist.
     * Throws Kaili\DirectoryException because the provided directory doesn't exist.
     * @test
     * @expectedException \Kaili\DirectoryException
     */
    public function test_factory_not_exist()
    {
        Directory::factory(ROOT.DS.'test_dir');
    }
    
    /**
     * Test for Directory::create()
     * @test
     */
    public function test_create()
    {
        $object = Directory::create(ROOT.DS.'test_dir');
        $this->assertEquals($object->get_path(), ROOT.DS.'test_dir');
    }
    
    /**
     * Test for Directory::create()
     * The Directory already exist.
     * Throws Exception because provided path is an already existent Directory
     * @test
     * @expectedException \Kaili\DirectoryException
     */
    public function test_create_exists()
    {
        Directory::create(ROOT.DS.'application');
    }
    
}

?>
